#!/usr/bin/env perl

use strict;
use warnings;

foreach my $app (@ARGV) {
    my $orig_dir = "$ENV{PWD}/$app";
    my $link_dir = read_target($app);

    -d $link_dir
        or mkdir($link_dir)
        or die "unable to create directory $link_dir";

    foreach my $orig_file (<$orig_dir/*>) {
        my $orig_file_name = basename($orig_file);
        my $link_file = $link_dir . "/" . expand_dotfile($orig_file_name);

        if ($orig_file_name eq "TARGET") {
            next;
        }

        symlink($orig_file, $link_file)
            or die "unable to link $link_file";
        print("$orig_file -> $link_file\n");
    }
}

sub read_target {
    my ($app) = @_;
    my $target = "$app/TARGET";

    open(my $fd, "<", $target)
        or die "unable to open $target";
    my $content = do { undef $\; <$fd> };
    close($fd)
        or die "unable to close $target";

    $content =~ s/^\s+|\s+$//g; # trim whitespace
    $content =~ s/~/$ENV{HOME}/g; # expand tilde (~)
    return $content;
}

# get last component of file path
sub basename {
    my ($file_path) = @_;
    (my $basename = $file_path) =~ s/.+\/(.+)$/$1/;

    return $basename
}

# transform strings of the form "dot.zshrc" -> ".zshrc"
sub expand_dotfile {
    my ($file_path) = @_;
    $file_path =~ s/dot\.(.+)$/\.$1/;

    return $file_path;
}

